"""Sealed check for kata 003 (cron-next).

Baked (expr, after, expected) triples — expected values were generated by a
reference implementation and hand-verified (leap-year, dom/dow OR, weekday skips).
"""
from __future__ import annotations

import re
import types
from datetime import datetime

CASES = [
    ("*/15 * * * *",   "2026-01-01T10:07", "2026-01-01T10:15"),
    ("0 0 * * *",      "2026-01-01T10:07", "2026-01-02T00:00"),
    ("0 9 * * 1-5",    "2026-07-11T12:00", "2026-07-13T09:00"),  # Sat -> Mon 9am
    ("0 0 1,15 * 3",   "2026-07-01T00:00", "2026-07-08T00:00"),  # dom OR dow(Wed)
    ("59 23 31 12 *",  "2026-06-01T00:00", "2026-12-31T23:59"),
    ("0-30/10 * * * *", "2026-01-01T00:03", "2026-01-01T00:10"),
    ("30 4 * * 0",     "2026-07-14T00:00", "2026-07-19T04:30"),  # Sunday
    ("0 12 29 2 *",    "2026-01-01T00:00", "2028-02-29T12:00"),  # leap year
]


def _extract_code(answer: str) -> str:
    m = re.search(r"```(?:python)?\n(.*?)```", answer.strip(), re.DOTALL)
    return (m.group(1) if m else answer).strip()


def check(answer: str, inputs_dir: str):
    total = len(CASES)
    mod = types.ModuleType("cron")
    try:
        exec(compile(_extract_code(answer), "cron.py", "exec"), mod.__dict__)
        next_run = mod.next_run
    except Exception as e:
        return 0, total, [f"module has no working next_run ({e})"]

    errors = []
    for expr, after, want in CASES:
        try:
            got = next_run(expr, datetime.fromisoformat(after))
            got_iso = got.replace(second=0, microsecond=0).isoformat()
        except Exception as e:
            errors.append(f"{expr!r} after {after}: raised {e}")
            continue
        if got_iso != datetime.fromisoformat(want).isoformat():
            errors.append(f"{expr!r} after {after}: got {got_iso}, expected {want}")
    return total - len(errors), total, errors
